# Generated by Django 4.2.7 on 2024-03-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_events_log_date_events_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='userID',
        ),
    ]
