# Generated by Django 4.2.7 on 2024-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_events_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='userID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
