# Generated by Django 4.2.7 on 2024-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_events_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='username',
            field=models.CharField(default='Caakee', max_length=300),
            preserve_default=False,
        ),
    ]
