# Generated by Django 4.2.7 on 2024-03-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_name_alter_event_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='log_date',
            field=models.DateTimeField(default='19.03.2024 21:29:08'),
        ),
    ]
