# Generated by Django 4.2.7 on 2024-03-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='log_date',
            field=models.DateTimeField(verbose_name='date logged'),
        ),
    ]
