# Generated by Django 4.2.7 on 2024-03-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='userID',
        ),
    ]
