# Generated by Django 4.2.7 on 2024-04-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_pic.jpg', upload_to='profile_images'),
        ),
    ]
